[package]
name = "vkc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.1"
ash-window = "0.10.0"
raw-window-handle = "0.3.4"
bytemuck = {version = "1.7.*", features=["derive"]}

