name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Vulkan SDK
      # You may pin to the exact commit or the version.
      # uses: humbletim/setup-vulkan-sdk@099bb52745ef25d99440fc15b6004582867d19c9
      uses: humbletim/setup-vulkan-sdk@v1.0.3
      with:
        # specify a Vulkan SDK release version, e.g. 1.2.162.1 (or git branch like sdk-1.2.162)
        vulkan-version: 1.2
        # specify a linux-specific Vulkan SDK release version, e.g. 1.2.162.1 (or git branch like sdk-1.2.162)
        vulkan-version-linux: 1.2
        # specify a windows-specific Vulkan SDK release version, e.g. 1.2.162.1 (or git branch like sdk-1.2.162)
        vulkan-version-windows: 1.2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
